<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT ROOT (#PCDATA)>
<!ELEMENT Customer (#PCDATA)>
<!ELEMENT Order (#PCDATA)>
<!ELEMENT OrderDetail (#PCDATA)>
]>
<note>
<to>BMSTU</to>
<from>Artur</from>
<heading>Lab5</heading>
<body>
	<ROOT>  
		<Customer CustomerID="VINET" ContactName="Paul Henriot">  
		   <Order OrderID="10248" CustomerID="VINET" EmployeeID="5"   
				  OrderDate="1996-07-04T00:00:00">  
			  <OrderDetail ProductID="11" Quantity="12"/>  
			  <OrderDetail ProductID="42" Quantity="10"/>  
		   </Order>  
		</Customer>  
		<Customer CustomerID="LILAS" ContactName="Carlos Gonzlez">  
		   <Order OrderID="10283" CustomerID="LILAS" EmployeeID="3"   
				  OrderDate="1996-08-16T00:00:00">  
			  <OrderDetail ProductID="72" Quantity="3"/>  
		   </Order>  
		</Customer>  
	</ROOT>
</body>
</note>